<?php
/**
 * @file
 * Functions for media_theplatform_mpx.module.
 */

define('MPX_PATH_ADMIN', 'admin/config/media/theplatform');
define('MPX_PATH_PLAYER', 'admin/content/media/mpxplayer');
define('MPX_PATH_VIDEO', 'admin/content/media/mpxmedia');

// A registry of variable_get defaults.
include_once ('includes/media_theplatform_mpx.variables.inc');
// Hooks and callbacks for integrating with File Entity module for display.
include_once ('includes/media_theplatform_mpx.formatters.inc');

// Helper functions.
include_once ('media_theplatform_mpx.admin.inc');
include_once ('media_theplatform_mpx.browser.inc');
include_once ('media_theplatform_mpx.helpers.php');
include_once ('media_theplatform_mpx.player.php');
include_once ('media_theplatform_mpx.video.php');


/**
 * Implements hook_menu().
 */
function media_theplatform_mpx_menu() {
  $items = array();
  $items[MPX_PATH_ADMIN] = array(
    'title' => 'Media: thePlatform mpx settings',
    'description' => 'Configure thePlatForm mpx integration settings.',
    'page callback' => 'media_theplatform_mpx_page_account',
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('administer mpx account'),
  );
  $items[MPX_PATH_PLAYER] = array(
    'title' => 'mpxPlayers',
    'page callback' => 'media_theplatform_mpx_page_mpx_players',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer media'),
    'weight' => 30,
  );
  $items[MPX_PATH_VIDEO] = array(
    'title' => 'mpxMedia',
    'page callback' => 'media_theplatform_mpx_page_mpx_videos',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer media'),
    'weight' => 40,
  );
  return $items;
}

/**
 * Implements hook_init().
 */
function media_theplatform_mpx_init() {
  // Add module CSS.
  drupal_add_css(drupal_get_path('module', 'media_theplatform_mpx') . '/css/media_theplatform_mpx.css', array(
    'group' => CSS_DEFAULT,
    'type' => 'file',
    'every_page' => TRUE)
  );
  // Add thePlatform Player Runtimes to <head>.
  $preferred_runtimes_meta = array(
    '#type' => 'html_tag',
    '#tag' => 'meta',
    '#attributes' => array(
      'name' => 'tp:PreferredRuntimes',
      'content' => media_theplatform_mpx_variable_get('runtimes'),
    ),
  );
  drupal_add_html_head($preferred_runtimes_meta, 'meta_tp_preferred_runtimes');
}

/**
 * Implements hook_theme().
 */
function media_theplatform_mpx_theme($existing, $type, $theme, $path) {
  return array(
    'media_theplatform_mpx_video' => array(
      'variables' => array(
        'uri' => NULL,
      ),
      'file' => 'media_theplatform_mpx.theme.inc',
      'path' => $path . '/includes/themes',
      'template' => 'media-theplatform-mpx-video',
    ),
  );
}

/**
 * Implements hook_media_internet_providers().
 */
function media_theplatform_mpx_media_internet_providers() {
  return array(
    'MediaInternetThePlatformMpxHandler' => array(
      'title' => 'All media from thePlatform mpx must be imported and cannot be added on this tab.',
    ),
  );
}

/**
 * Implements hook_stream_wrappers().
 */
function media_theplatform_mpx_stream_wrappers() {
  return array(
    'mpx' => array(
      'name' => t('mpx videos'),
      'class' => 'MediaThePlatformMpxStreamWrapper',
      'description' => t('Videos provided by ThePlatform.'),
      'type' => STREAM_WRAPPERS_READ_VISIBLE,
    ),
  );
}

/**
 * Implements hook_ctools_plugin_api().
 */
function media_theplatform_mpx_ctools_plugin_api($owner, $api) {
  static $api_versions = array(
    'file_entity' => array(
      'file_default_displays' => 1,
    ),
  );
  if (isset($api_versions[$owner][$api])) {
    return array('version' => $api_versions[$owner][$api]);
  }
}

/**
 * Implements hook_media_parse().
 *
 * @todo This hook should be deprecated. Refactor Media module to not call it
 *   any more, since media_internet should be able to automatically route to the
 *   appropriate handler.
 */
function media_theplatform_mpx_media_parse($embed_code) {
  module_load_include('media_theplatform_mpx', 'inc', 'includes/MediaInternetThePlatformMpxHandler');
  $handler = new MediaInternetThePlatformMpxHandler($embed_code);
  return $handler->parse($embed_code);
}


/**
 * Implements hook_file_delete().
 */
function media_theplatform_mpx_file_delete($file) {
  // If its a mpx file, delete its record in mpx_player or mpx_video.
  if ($file->filemime == 'video/mpx') {
    $wrapper = file_stream_wrapper_get_instance_by_uri($file->uri);
    $parts = $wrapper->get_parameters();

    // Deleting a Player:
    // This is assuming that you know you're doing.
    // If a user tries to delete through the Media forms, they can't submit if the Player is referenced by other mpxMedia.
    // If they're just deleting this record in the database or thru PHP, well, it could kill other mpxMedia Files that reference it and then good luck to you.
    if ($parts['mpx_type'] == 'player') {
      $player = media_theplatform_mpx_get_mpx_player_by_fid($file->fid);
      db_delete('mpx_player')->condition('fid', $file->fid)->execute();
      $deleted_id = $player['player_id'];
    }

    // Deleting a Video:
    elseif ($parts['mpx_type'] == 'video') {
      // Check for other mpxMedia Files that also reference this mpx_video.
      $guid = $parts['mpx_id'];
      $files = db_select('file_managed', 'f')
        ->fields('f')
        ->condition('fid', $file->fid, '!=')
        ->condition('uri', 'mpx://m/' . $guid . '/%', 'LIKE')
        ->execute()
        ->fetchAll();

      // If other files exist:
      if ($files) {
        // Update mpx_video record with the next fid.
        $update = db_update('mpx_video')
          ->fields(array(
            'fid' => $files[0]->fid,
          ))
          ->condition('guid', $guid, '=')
          ->execute();
      }
      // Else no other files exist:
      else {
        // @todo - store video_id
        // Delete the mpx_video record.
        $deleted_id = db_delete('mpx_video')->condition('guid', $guid)->execute();
        // Log deletion.
        global $user;
        $log = array(
          'uid' => $user->uid,
          'type' => $parts['mpx_type'],
          'type_id' => $deleted_id,
          'action' => 'deleted',
          'details' => 'deleted file id' . $file->fid,
        );
        media_theplatform_mpx_insert_log($log);
      }
    }

  }
}

/**
 * Write data from given array $data into the mpx_log table.
 */
function media_theplatform_mpx_insert_log($data) {
  $insert = db_insert('mpx_log')
  ->fields(array(
    'uid' => $data['uid'],
    'type' => $data['type'],
    'type_id' => $data['type_id'],
    'action' => $data['action'],
    'timestamp' => REQUEST_TIME,
    'details' => $data['details'],
  ))
  ->execute();
}

/**
 * Implements hook_cron().
 */
function media_theplatform_mpx_cron() {
  // Don't do anything if we don't have signIn token.
  if (!media_theplatform_mpx_variable_get('token')) {
    return;
  }
  // Check if username/password are still valid.
  $username = media_theplatform_mpx_variable_get('username');
  $pass = media_theplatform_mpx_variable_get('password');
  if ($username && $pass) {
    $valid_login = media_theplatform_mpx_signin($username, $pass);
    if (!$valid_login) {
      watchdog('media_theplatform_mpx', 'Invalid username/password for thePlatform.');
    }
    else {
      if (media_theplatform_mpx_variable_get('cron_players')) {
        media_theplatform_mpx_import_all_players('cron');
      }
      if (media_theplatform_mpx_variable_get('cron_videos')) {
        media_theplatform_mpx_import_all_videos('cron');
      }
    }
  }
}

/**
 * Implements hook_permission().
 */
function media_theplatform_mpx_permission() {
  return array(
    'administer mpx account' => array(
      'title' => t('Administer mpx Account'),
      'description' => t('Can enter administrator login for thePlatform, set mpx Import Account'),
    ),
    'sync mpx_player' => array(
      'title' => t('Sync mpxPlayers manually'),
      'description' => t('Can access mpxPlayers Sync form.'),
    ),
    'administer mpx_video settings' => array(
      'title' => t('Administer mpxMedia'),
      'description' => t('Can set Import Feed, Default mpxPlayer, Sync mpxMedia form.'),
    ),
    'sync mpx_video' => array(
      'title' => t('Sync mpxMedia manually'),
      'description' => t('Can access Sync mpxMedia form.'),
    ),
  );
}

/**
 * Implements hook_form_alter().
 */
function media_theplatform_mpx_form_alter(&$form, &$form_state, $form_id) {
  // Check if it's media: single file delete form OR bulk media delete form.
  $message = FALSE;
  $media_file_delete_form = $form['#id'] == 'media-admin' && isset($form['operation']) && $form['operation']['#value'] == 'delete';
  if ($form['#id'] == 'media-multiple-delete-confirm' || $media_file_delete_form) {
    foreach ($form['files'] as $fid) {
      if (isset($fid['#value'])) {
        $file = file_load($fid['#value']);
        if ($file->filemime == 'video/mpx' && media_theplatform_mpx_get_files_by_player_fid($file->fid)) {
          drupal_set_message(t('mpxPlayer cannot be deleted because it is referenced by other mpxMedia Files.'), 'error');
          unset($form['actions']['submit']);
          unset($form['description']);
        }
      }
    }
  }
}
